dingo/urls.py
# dingo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dingo.api import router

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('', include("greetings.urls")),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maths/urls.py
from django.urls import path

from maths.views import math, add, sub, mul, div, maths_list, math_details, results_list

app_name="maths"

urlpatterns = [
    path('', math),
    path('add/<int:a>/<int:b>', add),
    path('sub/<int:a>/<int:b>', sub),
    path('mul/<int:a>/<int:b>', mul),
    path('div/<int:a>/<int:b>', div),
    path('histories/', maths_list, name="list"),
    path('histories/<int:id>', math_details, name="details"),
    path('results/', results_list, name="results"),

]

posts/urls.py
from django.urls import path
from django.views.generic import ListView

from posts.models import Post
from posts.views import posts_list, post_details, authors_list, author_details

app_name = "posts"

urlpatterns = [
    path('', posts_list, name="list"),
    path('<int:id>', post_details, name="details"),
    path('authors', authors_list, name="authors"),
    path('authors/<int:id>', author_details, name="author"),
    path('list', ListView.as_view(model=Post), name="posts_list"),
]

maths/models.py
from django.db import models

OPERATION_CHOICES = (
    ("add", "add"),
    ("sub", "sub"),
    ("mul", "mul"),
    ("div", "div"),
)


class Math(models.Model):
    operation = models.CharField(max_length=5, choices=OPERATION_CHOICES)
    a = models.IntegerField()
    b = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    result = models.ForeignKey(
        "maths.Result",
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"id:{self.id}, a={self.a}, b={self.b}, op={self.operation}"

    class Meta:
        ordering = ["-id"]

class Result(models.Model):
    value = models.FloatField(blank=True, null=True, unique=True)
    error = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        unique=True
    )

    def __str__(self):
        return f"value: {self.value} | error: {self.error}"

maths/forms.py
from django import forms

from maths.models import Result


class ResultForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        value = cleaned_data.get('value')
        error = cleaned_data.get('error')

        if value and error:
            raise forms.ValidationError("Podaj tylko jedną z wartości")
        elif not (value or error):
            raise forms.ValidationError("Nie podano żadnej wartości!")

    class Meta:
        model = Result
        fields = ["value", "error"]

maths/views.py
# maths/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages

from maths.forms import ResultForm
from maths.models import Math, Result


def math(request):
    return render(
        request=request,
        template_name="maths/../templates/main.html",
        context={}
    )


def add(request, a, b):
    wynik = a + b
    c = {"a": a, "b": b, "operacja": "+", "wynik": wynik, "title": "dodawanie"}

    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='add', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def sub(request, a, b):
    wynik = a - b
    c = {"a": a, "b": b, "operacja": "-", "wynik": wynik, "title": "odejmowanie"}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='sub', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def mul(request, a, b):
    wynik = a * b
    c = {"a": a, "b": b, "operacja": "*", "wynik": wynik, "title": "mnożenie"}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='mul', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def div(request, a, b):
    if b == 0:
        wynik = "Error"
        messages.add_message(request, messages.ERROR, "Dzielenie przez zero!!")
    else:
        wynik = a / b
    c = {"a": a, "b": b, "operacja": "/", "wynik": wynik, "title": "dzielenie"}
    if wynik == "Error":
        result = Result.objects.get_or_create(error=wynik)[0]
    else:
        result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='add', a=a, b=b, result=result)
    Math.objects.create(operation='add', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )

@login_required
def maths_list(request):
    operation = request.GET.get('operation')
    if operation:
        maths = Math.objects.filter(operation=operation)
    else:
        maths = Math.objects.all()
    paginator = Paginator(maths, 5)
    page_number = request.GET.get('page')
    maths = paginator.get_page(page_number)
    return render(
        request=request,
        template_name="maths/list.html",
        context={"maths": maths, 'active': "maths"}
    )


def math_details(request, id):
    math = Math.objects.get(id=id)
    return render(
        request=request,
        template_name="maths/details.html",
        context={"math": math, 'active': "maths"}
    )


def results_list(request):
    if request.method == "POST":
        form = ResultForm(data=request.POST)

        if form.is_valid():
            Result.objects.get_or_create(**form.cleaned_data)
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowy Result!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = ResultForm()
    results = Result.objects.all()
    return render(
        request=request,
        template_name="maths/results.html",
        context={
            "results": results,
            "form": form
        }
    )

maths/templates/maths/details.html
{% extends "main.html" %}

{% block title %}Maths list{% endblock %}


{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "maths" "maths:list" %}
    {% breadcrumb "details" "" %}
{% endblock %}
{% block content %}


    {% render_breadcrumbs %}

    <table>
        <tr>
            <th>Operation</th>
            <td>{{ math.operation }}</td>
        </tr>
        <tr>
            <th>a</th>
            <td>{{ math.a }}</td>
        </tr>
        <tr>
            <th>b</th>
            <td>{{ math.b }}</td>
        </tr>
        <tr>
            <th>Created:</th>
            <td>{{ math.created }}</td>
        </tr>
        <tr>
            <th>Result</th>
            <td>{{ math.result }}</td>
        </tr>
    </table>
    <a href="{% url "maths:list" %}">back</a>
{% endblock %}

maths/templates/maths/list.html
{% extends "main.html" %}

{% block title %}Maths list{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "maths" "maths.views.maths_list" %}
{% endblock %}

{% block content %}


    {% render_breadcrumbs %}

    <div class="search">
        <form>
            <label for="operation">Operacja</label>
            <input type="text" id="operation" name="operation">
            <input type="submit" value="szukaj">
        </form>
    </div>
    <div class="row">
        <div class="col-6">
            <table class="table table-stripped">

                <tr>
                    <th>id</th>
                    <th>a</th>
                    <th>b</th>
                    <th>op</th>
                    <th>result</th>
                </tr>
                {% for m in maths %}
                    <tr>
                        <td><a href="{% url 'maths:details' id=m.id %}">{{ m.id }}</a></td>
                        <td>{{ m.a }}</td>
                        <td>{{ m.b }}</td>
                        <td>{{ m.operation }}</td>
                        <td>{% if m.result.value %}{{ m.result.value }}{% else %}{{ m.result.error }}{% endif %}</td>
                    </tr>
                {% endfor %}

            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center pagination-sm">
                    {% if maths.has_previous %}
                        <!-- If it ain't a search result display, don't append the search query
                             to the URL. -->
                        {% if not search %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'maths:list' %}?page={{ maths.previous_page_number }}"
                                   tabindex="-1">Previous</a>
                            </li>
                        {% else %}
                            <!-- Append the searched query to the URL, so that on a search results page,
                                 the pagination don't revert to listing all the listview items. -->
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'maths:list' %}?{{ search }}&page={{ maths.previous_page_number }}"
                                   tabindex="-1">Previous</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    {% for object in maths.paginator.page_range %}
                        <li class="page-item"><a class="page-link"
                                                 href="{% url 'maths:list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                    {% endfor %}
                    {% if maths.has_next %}
                        {% if not search %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'maths:list' %}?page={{ maths.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'maths:list' %}?{{ search }}&page={{ maths.next_page_number }}">Next</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
        <div class="col-6">
            <h1>Statistics</h1>
        </div>
    </div>




{% endblock %}

maths/templates/maths/main.html
{% load bootstrap4 %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "/" %}
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {# Custom CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'maths/css/style.css' %}">

</head>
<body>
<div class="container">

    <div id="header">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <h1>DINGO</h1><small>working space with perspective...</small>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item {% if active == 'home' %}active{% endif %}">
                            <a class="nav-link" href="{% url "welcome" %}">Home</a>
                        </li>

                        <li class="nav-item {% if active == 'maths' %}active{% endif %}">
                            <a class="nav-link" href="{% url "maths:list" %}">Maths</a>
                        </li>
                        <li class="nav-item {% if active == 'posts' %}active{% endif %}">
                            <a class="nav-link" href="{% url "posts:list" %}">Posts</a>
                        </li>
                        <li class="nav-item {% if active == 'about' %}active{% endif %}">
                            <a class="nav-link" href="{% url "about" %}">About</a>
                        </li>
                        <li class="nav-item {% if active == 'contact' %}active{% endif %}">
                            <a class="nav-link" href="{% url "contact" %}">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    {% bootstrap_messages %}
    <div id="inner-content">
        {% block content %}
            To jest blok kodu. W innych szablonach możemy go nadpisać
        {% endblock %}
    </div>
</div>
</body>
</html>

maths/templates/maths/operation.html
{% extends "main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    Wynik operacji {{ a }} {{ operacja }} {{ b }} wynosi {{ wynik }}
{% endblock %}

maths/templates/maths/results.html
{% extends "main.html" %}

{% block title %}Maths list{% endblock %}

{% block content %}


    <ul>
        {% for r in results %}
            <li>{{ r }}</li>
        {% endfor %}
    </ul>


    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="go">
    </form>

{% endblock %}

maths/templates/maths/xxx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dodawanie</title>


    <link rel="stylesheet" type="text/css" href="/static/maths/css/style.css">


    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
            src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>
<div id="content">



    <div id="inner-content">

        Wynik operacji 1 + 2 wynosi 3

    </div>
</div>
</body>
</html>