dingo/urls.py
# dingo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dingo.api import router

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('', include("greetings.urls")),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path

from greetings.views import about, contact, welcome

urlpatterns = [
    path('', welcome, name="welcome"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
]

maths/urls.py
from django.urls import path

from maths.views import math, add, sub, mul, div, maths_list, math_details, results_list

app_name="maths"

urlpatterns = [
    path('', math),
    path('add/<int:a>/<int:b>', add),
    path('sub/<int:a>/<int:b>', sub),
    path('mul/<int:a>/<int:b>', mul),
    path('div/<int:a>/<int:b>', div),
    path('histories/', maths_list, name="list"),
    path('histories/<int:id>', math_details, name="details"),
    path('results/', results_list, name="results"),

]

posts/urls.py
from django.urls import path
from django.views.generic import ListView

from posts.models import Post
from posts.views import posts_list, post_details, authors_list, author_details

app_name = "posts"

urlpatterns = [
    path('', posts_list, name="list"),
    path('<int:id>', post_details, name="details"),
    path('authors', authors_list, name="authors"),
    path('authors/<int:id>', author_details, name="author"),
    path('list', ListView.as_view(model=Post), name="posts_list"),
]

greetings/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.

def hello(request, name="World!"):
    return HttpResponse(f"Hello {name}")


def about(request):
    return render(
        request=request,
        template_name="greetings/about.html",
        context={}
    )


def contact(request):
    return render(
        request=request,
        template_name="greetings/contact.html",
        context={}
    )


def welcome(request):
    return render(
        request=request,
        template_name="greetings/welcome.html",
        context={}
    )

greetings/templates/greetings/about.html
{% extends "main.html" %}

{% block content %}
    <h1>O nas</h1>
{% endblock %}

greetings/templates/greetings/contact.html
{% extends "main.html" %}

{% block content %}
    <h1>Dane kontaktowe: </h1>
{% endblock %}

greetings/templates/greetings/welcome.html
{% load bootstrap4 %}
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {# Custom CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'greetings/css/style.css' %}">
    <style>

    </style>

</head>
<body>
<div class="container">
    <div class="row">
        <a class="col-3 text-center button" href="{% url "about" %}">About</a>
        <a class="col-3 text-center button" href="{% url "posts:list" %}">Posts</a>
        <a class="col-3 text-center button" href="{% url "maths:list" %}">Maths</a>
        <a class="col-3 text-center button" href="{% url "contact" %}">Contact</a>
    </div>
    <h1>DINGO</h1>
</div>
</body>
</html>