dingo/urls.py
# dingo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dingo.api import router

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('', include("greetings.urls")),
    path('maths/', include("maths.urls")),
    path('posts/', include("posts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.views.generic import ListView

from posts.models import Post
from posts.views import posts_list, post_details, authors_list, author_details

app_name = "posts"

urlpatterns = [
    path('', posts_list, name="list"),
    path('<int:id>', post_details, name="details"),
    path('authors', authors_list, name="authors"),
    path('authors/<int:id>', author_details, name="author"),
    path('list', ListView.as_view(model=Post), name="posts_list"),
]

posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('posts.Author', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d', null=True, blank=True)
    tags = models.ManyToManyField("posts.Tag", related_name="posts")
    def __str__(self):
        return f"<Post: Author:{self.author}, Title:{self.title}>"


class Author(models.Model):
    nick = models.CharField(max_length=50, unique=True)
    email = models.EmailField()

    def __str__(self):
        return f"<Author: {self.nick}>"


class Tag(models.Model):
    word = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.word

posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        fields = ["title", "content", "author", "image", "tags"]


class AuthorForm(forms.Form):
    nick = forms.CharField()
    email = forms.EmailField()

posts/views.py
from django.contrib import messages
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

from posts.forms import PostForm, AuthorForm
from posts.models import Post, Author


def posts_list(request):
    posts = Post.objects.all()
    form = PostForm()
    if request.method == "POST":
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Dodano nowy Post!!"
            )
            form = PostForm()
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors["__all__"]
            )
    return render(
        request=request,
        template_name="posts/list.html",
        context={"posts": posts, "form": form, 'active': 'posts'}
    )


def post_details(request, id):
    post = Post.objects.get(pk=id)
    return render(
        request=request,
        template_name="posts/details.html",
        context={"post": post, 'active': "posts"}
    )


def authors_list(request):
    authors = Author.objects.all()
    form = AuthorForm()
    if request.method == "POST":
        form = AuthorForm(data=request.POST)
        if form.is_valid():
            Author.objects.create(**form.cleaned_data)
            messages.add_message(
                request,
                messages.SUCCESS,
                "Dodano Autora!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors["__all__"]
            )
    return render(
        request=request,
        template_name="posts/authors.html",
        context={'authors': authors, 'form': form}
    )


def author_details(request, id):
    author = Author.objects.get(pk=id)
    return render(
        request=request,
        template_name="posts/author.html",
        context={'author': author}
    )


class PostsList(ListView):
    model = Post
    template_name = "posts/list.html"
    form_class = PostForm
    context_object_name = "posts"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = PostForm()
        return context

posts/templates/posts/author.html
{% extends "main.html" %}

{% block title %}Autor{% endblock %}

{% block content %}
    <h1>Autor</h1>
    <h2>{{ author.nick }}</h2>
    <h2>{{ author.email }}</h2>

    <a href="{% url "posts:authors" %}">back</a>
{% endblock %}

posts/templates/posts/authors.html
{% extends "main.html" %}

{% block title %}Autorzy{% endblock %}

{% block content %}
    <ul>
        {% for a in authors %}
            <li><a href="{% url "posts:author" a.id %}">{{ a.nick }}</a></li>
        {% endfor %}
    </ul>

    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Dodaj">
        </form>


    </div>
{% endblock %}

posts/templates/posts/details.html
{% extends "main.html" %}

{% block title %}Post{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "posts" "posts:list" %}
{% endblock %}

{% block content %}
    {%  render_breadcrumbs %}
    <h1>{{ post.title }}</h1>
    <h2>{{ post.author.nick }} | {{ post.created }}</h2>
    <p>
        {{ post.content }}
    </p>
    <div><img src="{{ post.image.url }}"></div>
    <a href="{% url "posts:list" %}">back</a>
{% endblock %}

posts/templates/posts/list.html
{% extends "main.html" %}

{% block title %}Posty{% endblock %}

{% load bootstrap4 %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "posts" "posts:list" %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <div class="row">
        <div class="col-6">
            <table class="table">
            <tr>
                <th>Tytuł</th>
                <th>Autor</th>
                <th>Data</th>
            </tr>
                {% for p in posts %}
                    <tr>
                        <td><a href="{% url "posts:details" p.id %}">{{ p.title }}</a></td>
                        <td>{{ p.author.nick }}</td>
                        <td>{{ p.created }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-6">
            {% if perms.posts.add_post %}
            <h2>Dodaj nowy</h2>
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {% bootstrap_form form  %}
                <input type="submit" value="Dodaj">
            </form>
            {% else %}
            {% endif %}

        </div>
    </div>

{% endblock %}

posts/templates/posts/post_list.html
{% extends "main.html" %}

{% block title %}Posty{% endblock %}

{% load bootstrap4 %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "posts" "posts:list" %}
{% endblock %}

{% block content %}
    {% render_breadcrumbs %}
    <div class="row">
        <div class="col-6">
            <table class="table">
            <tr>
                <th>Tytuł</th>
                <th>Autor</th>
                <th>Data</th>
            </tr>
                {% for p in post_list %}
                    <tr>
                        <td><a href="{% url "posts:details" p.id %}">{{ p.title }}</a></td>
                        <td>{{ p.author.nick }}</td>
                        <td>{{ p.created }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-6">
        </div>
    </div>

{% endblock %}